services:
  # mongodb:
  #   image: tsivyal/my-mongo-image:latest
  #   container_name: my_mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: always
  #   networks:
  #     - backend-network

  backend:
    build:
      context: ./ 
      dockerfile: Dockerfile-go  
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
        # Mount the Docker socket
      - C:/Users/OWNER/.kube:/root/.kube:ro
    environment:
      - MONGO_URI=${MONGO_URI}
      - VARIABLE_NAME=VALUE
      - KUBECONFIG=/root/.kube/config
      
    # depends_on:
    #   - mongodb
    networks:
      - backend-network
    restart: always

  frontend:
    image: tsivyal/nuxt-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - backend-network
    restart: always

volumes:
  answer-volume:  # Shared volume for communication between containers
  mongo-data:     # Persistent storage for MongoDB data

networks:
  backend-network:
    driver: bridge  # Define a shared network for communication between containers
