# Use Go image as the base for the build stage
FROM golang:1.23-alpine as builder

# --- NETFREE CERTIFICATE INSTALLATION ---
ADD https://netfree.link/dl/unix-ca.sh /home/netfree-unix-ca.sh 
RUN cat /home/netfree-unix-ca.sh | sh
ENV NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt
ENV REQUESTS_CA_BUNDLE=/etc/ca-bundle.crt
ENV SSL_CERT_FILE=/etc/ca-bundle.crt
# --- END OF NETFREE CERTIFICATE INSTALLATION ---

# Install necessary packages, including curl, bash, ca-certificates, nodejs, python3, and npm
RUN apk add --no-cache \
    curl \
    bash \
    ca-certificates \
    nodejs \
    npm \
    python3 \
    py3-pip && \
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.27.3/bin/linux/amd64/kubectl" && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

# Set the working directory inside the container
WORKDIR /app

# Copy all project files into the container
COPY . .

# Copy the .env file into the container
COPY .env .env

# Install Go dependencies
RUN go mod tidy

# Build the Go application
RUN go build -o backend .

# Command to run the backend application (or an entrypoint for your app)
CMD ["go", "run", "main.go"]
