# Use Go image as the base for the build stage
FROM golang:1.23-alpine as builder

# --- NETFREE CERTIFICATE INSTALLATION ---
ADD https://netfree.link/dl/unix-ca.sh /home/netfree-unix-ca.sh 
RUN cat /home/netfree-unix-ca.sh | sh
ENV NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt
ENV REQUESTS_CA_BUNDLE=/etc/ca-bundle.crt
ENV SSL_CERT_FILE=/etc/ca-bundle.crt
# --- END OF NETFREE CERTIFICATE INSTALLATION ---

# Install additional necessary packages
RUN apk add --no-cache \
curl \
bash

# Set the working directory inside the container
WORKDIR /app

# Copy all project files into the container
COPY . .

# Copy the .env file into the container
COPY .env .env

# Install Go dependencies
RUN go mod tidy

# Build the Go application
RUN go build -o backend .

# Run the backend application
CMD ["go", "run", "main.go"]
