FROM python:latest
# --- NETFREE CERT INTSALL ---
    ADD https://netfree.link/dl/unix-ca.sh /home/netfree-unix-ca.sh 
    RUN cat  /home/netfree-unix-ca.sh | sh
    ENV NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt
    ENV REQUESTS_CA_BUNDLE=/etc/ca-bundle.crt
    ENV SSL_CERT_FILE=/etc/ca-bundle.crt
    # --- END NETFREE CERT INTSALL ---

WORKDIR /usr/src/app

# העתקת כל הקבצים לתוך המיכל
COPY . .

# התקנת Flask דרך pip עם חיבור לא מאומת
# RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org flask

# הפעלת הסקריפט 'answer.py' בעזרת פייתון
# CMD ["python3", "answer.py"]
