services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - "8080:8080"
    environment:
        - DB_HOST=${MONGO_URI}
    depends_on:
      - mongodb
    restart: always

  python:
    image: python:latest
    container_name: python-container
    volumes:
      - answer-volume:/tmp
    command: python3 /tmp/answer.py
    restart: on-failure

  nodejs:
    image: nodejs-runner  # השם שניתן ל-image שנבנה עבור Node.js
    container_name: nodejs-container
    volumes:
      - answer-volume:/tmp
    command: node /tmp/answer.js
    restart: on-failure

volumes:
  answer-volume:
  mongo-data:
