services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=TsivyaL
      - MONGO_INITDB_ROOT_PASSWORD=MyName1sTsivya
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile-go
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mongodb://TsivyaL:MyName1sTsivya@mongodb:27017
    depends_on:
      - mongodb
    restart: always

  python:
    image: python:latest
    container_name: python-container
    volumes:
      - answer-volume:/tmp
    command: python3 /tmp/answer.py
    restart: on-failure
  csharp:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: csharp-container
    volumes:
      - answer-volume:/tmp
    command: bash -c "echo '$CODE' > /tmp/answer.cs && dotnet new console -o /tmp/csharp-app && cd /tmp/csharp-app && dotnet run"
    restart: on-failure
volumes:
  answer-volume:
  mongo-data:
