name: CI Pipeline

on:
  push:
    branches:
      - main  # תהליך זה יתבצע רק כאשר יהיה push ל-main
  pull_request:
    branches:
      - main  # אפשר להריץ גם על Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # שלב 1: קליטת הקוד מה-repository
    - name: Checkout code
      uses: actions/checkout@v2

    # שלב 2: הגדרת Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # שלב 3: התחברות ל-Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # שלב 4: בניית התמונה והעלאתה ל-Docker Hub
    - name: Build and push backend image
      run: |
        docker build -t tsivyal/leetcodebackend:latest .
        docker push tsivyal/leetcodebackend:latest

    # שלב 5: הרצת בדיקות (אם יש)
    - name: Run tests
      run: |
        cd backend
      #go test ./...  # אם יש לך בדיקות Go
