name: CI Pipeline

on:
  push:
    branches:
      - main  # The process will run only when there is a push to the main branch
  pull_request:
    branches:
      - main  # The process can also run on Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Login to Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image from your Dockerfile
    - name: Build Docker image
      run: |
        docker build -t tsivyal/leetcodebackend:latest .  # Build the image from your code using the Dockerfile

    # Step 5: Push the image to Docker Hub
    - name: Push Docker image to DockerHub
      run: |
        docker push tsivyal/leetcodebackend:latest  # Push the image to Docker Hub

    # Step 6: Run the Docker container
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 tsivyal/leetcodebackend:latest  # Run the container from the image we just created

    # Step 7: Run build or tests (if any)
    - name: Compile check
      run: |
        go build ./...  # Run your build or tests after building the image
