name: CI Pipeline

on:
  push:
    branches:
      - main  # This will trigger the CI process on push to the main branch
  pull_request:
    branches:
      - main  # This will trigger the CI process on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image and push it to Docker Hub
    - name: Build and push backend image
      run: |
        docker build -t tsivyal/leetcodebackend:latest .
        docker push tsivyal/leetcodebackend:latest

    # Step 5: Run tests (if there are any)
    - name: Run tests
      run: |
        cd backend
       # go test ./...  # Uncomment and run Go tests if you have them
