name: CI Pipeline

on:
  push:
    branches:
      - main  # התהליך יתבצע רק כאשר יהיה push ל-main
  pull_request:
    branches:
      - main  # אפשר להריץ גם על Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # שלב 1: קליטת הקוד מה-repository
    - name: Checkout code
      uses: actions/checkout@v2

    # שלב 2: הגדרת Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # שלב 3: התחברות ל-Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # שלב 4: משיכת התמונה מ-Docker Hub
    - name: Pull Docker Image from DockerHub
      run: |
        docker pull tsivyal/leetcodebackend:latest  # התמונה שלך ב-Docker Hub

    # שלב 5: הרצת הקונטיינר
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 tsivyal/leetcodebackend:latest  # הרצת הקונטיינר

    # שלב 6: הרצת בדיקות (אם יש)
    - name: Run tests
      run: |
        # הרץ את הבדיקות שלך אם יש
        # לדוגמה:
        # go test ./...
